import { useState, useEffect } from 'react';

let cachedData = null;

/**
 * Hook to load real Alpine snow data from the JSON generated by the data pipeline.
 * Falls back gracefully if the data file doesn't exist yet.
 */
export default function useSnowData() {
  const [data, setData] = useState(cachedData);
  const [loading, setLoading] = useState(!cachedData);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (cachedData) return;

    fetch('/data/alpine_snow_data.json')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((json) => {
        cachedData = json;
        setData(json);
        setLoading(false);
      })
      .catch((err) => {
        console.warn('Real data not available, using synthetic fallback:', err.message);
        setError(err.message);
        setLoading(false);
      });
  }, []);

  return { data, loading, error };
}

/**
 * Get elevation band data by index (0=Low, 1=Mid, 2=High).
 */
export function getBandData(data, bandIndex) {
  if (!data || !data.elevation_bands) return null;
  const bandNames = Object.keys(data.elevation_bands);
  if (bandIndex >= bandNames.length) return null;
  return { name: bandNames[bandIndex], ...data.elevation_bands[bandNames[bandIndex]] };
}

/**
 * Get all band names from the data.
 */
export function getBandNames(data) {
  if (!data || !data.elevation_bands) return ['Low Alps (< 1500m)', 'Mid Alps (1500-2500m)', 'High Alps (> 2500m)'];
  return Object.keys(data.elevation_bands);
}
